### ISSUE TITLE
Unable to run following test

### ISSUE THREAD

**Issue by reborg** [rachbowyer/keirin#1]
Hey Rachel,

I'm starting a clean JVM with Clojure, Keirin and logging libs on the classpath and following opts `-server -Xbatch -Xloggc:gc.out -XX:-TieredCompilation -Xmx1g -Xms1g`.

When I run the following:

```clojure
(require '[keirin.core :as k])
(let [xs (range 1000)] (k/bench (vec xs)))
```

I get:

`Exception Unable to get clean runs estimating number of executions. GC failures: 10. Compilation failures: 2.Class loading failures: 0.   keirin.core/estimate-num-executions (core.clj:399)`

**Comment by rachbowyer** [comment]
Thanks for commenting. I will change the code to make the exception clearer.

What is happening is that every time Keirin tries to do a timed run a garbage collection (gc) occurs. After 10 attempts it gives up. 

Detection of garbage collections is a core technique Keirin uses to ensure that its results are accurate. Any run in which a gc occurs is discarded as the time taken for the gc distorts the results.

Here are a couple of ways to fix the issue:
* Increase the amount of memory available (e.g to 4G) through the Xmx and Xms flags. The more heap space there is, the less chance of a gc.
* Reduce the time that the function runs for. By default a function under test is run for 300ms.  For example this could be reduced to 100ms using the parameter :min-execution-time 100. BTW the documentation incorrectly stated the parameter is :minimum-excecution-time - I have fixed this now.
